---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Populate ansible user name
      ansible.builtin.set_fact:
        ansible_user: "root"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Debug docker register
      become: true
      ansible.builtin.command:
        cmd: apt list libc6
      register: output

    - name: Debug docker
      ansible.builtin.debug:
        msg: $ {{ output  }}

  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: jakoblichterfeld.android_studio
